version: '3.1'

services:
  my_visualizr:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8090:8080"