version: '3.1'
services:

  wordpress:
    image: wordpress
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: abc123

  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: abc123